#:schema node_modules/wrangler/config-schema.json
name = "sublink-sing"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "5125e3ed1150424f906d95e98e6feed0" }
]
